name: Security Scanning

on:
  workflow_call:
  schedule:
    - cron: "0 2 * * 1"

jobs:
  trivy:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5

      - name: Setup trivy
        uses: aquasecurity/setup-trivy@v0.2.4
        with:
          cache: true
          version: latest

      - name: Run trivy configuration checks
        run: |
          trivy config . --config=.trivy.yaml --ignorefile=.trivyignore

      - name: Run trivy filesystem checks
        run: |
          trivy filesystem . --config=.trivy.yaml --ignorefile=.trivyignore --no-progress
